name: 'deploy docker'

on:
  push:
    tags:
      - "v2000"

jobs:

  release-docker-image-job:
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    permissions: write-all
    steps:
      - uses: actions/checkout@v4

      - uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: ${{ github.event.repository.name }}
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}



            